[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
polygonAmoy = "${POLYGON_AMOY_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"

[lint]
exclude_lints = [
    "mixed-case-variable",
    "pascal-case-struct",
    "mixed-case-function",
    "screaming-snake-case-immutable",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
